<!DOCTYPE html>
<html>
<head>
    <style>
        .listening-address {
            color: blue;
            background-color: lightgrey;
            text-decoration: none;
            padding: 10px;
            border-radius: 5px;
            font-family: Arial, sans-serif;
        }

        .listening-address:hover {
            color: white;
            background-color: darkblue;
        }
    </style>
</head>
<body>
    <a href="https://web.facebook.com/?_rdc=1&_rdr" class="listening-address">Facebook</a>
	<a href="https://web.facebook.com/?_rdc=1&_rdr" class="listening-address">Facebook</a>
	<a href="https://web.facebook.com/?_rdc=1&_rdr" class="listening-address">Facebook</a>
	<a href="https://web.facebook.com/?_rdc=1&_rdr" class="listening-address">Facebook</a>
	<a href="https://web.facebook.com/?_rdc=1&_rdr" class="listening-address">Facebook</a>
</body>
</html>
